CREATE TABLE FUNDRAISER(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ACCOUNT REAL,
    CURRENCY TEXT NOT NULL
);

CREATE TABLE CHARITY_BOX(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    IDENTIFIER VARCHAR(225) NOT NULL,
    FUNDRAISER_ID INT,
    FOREIGN KEY (FUNDRAISER_ID) REFERENCES FUNDRAISER(ID)
);

CREATE TABLE COLLECTED(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CHARITYBOX_ID INT,
    FOREIGN KEY (CHARITYBOX_ID) REFERENCES CHARITY_BOX(ID),
    AMOUNT REAL,
    CURRENCY TEXT NOT NULL
)